[tasks.render]
usage = '''
arg "<variant>" help="The resume variant to render" default="primary"
'''
description = "Render the resume"
run = '''
cd {{config_root}}/${usage_variant?}
reze render
cd {{config_root}}
'''

[tasks.watch]
description = "Render the resume with mise's file watcher"
run = '''
mise w -w {{config_root}} -c clear -f 'reze.toml' -f 'resume.toml' -f 'template.typ' render
'''
