output_dir = "../artifacts"
resume_data_path = "../resume.toml"
title = "jenny-family-medicine"

[typst]
template = "../template.typ"

[queries]
work = [
    { Hide = "Bouvé College of Health Sciences, Northeastern University" },
    { Hide = "Center for Academic Performance, UNTHSC" },
    { OverrideHighlights = { target = "Bouvé College of Health Sciences, Northeastern University", highlights = [
        "Led pre-exam recitations for first-year Doctor of Physical Therapy students and guided labs for identifying anatomical structures of the skull, brain, and spinal cord on models, human cadavers, and images of cross-sectional slices"
    ] } },
]
'clinical rotation' = [
    { HideDetail = "Psychiatry" },
    { HideDetail = "Emergency Medicine" },
    { HideDetail = "General Surgery" },
    { HideDetail = "Underserved" },
    { OverrideHighlights = { target = "Pulmonary/Sleep", highlights = [
        "Evaluated and managed common chief complaints such as shortness of breath, chronic cough, pulmonary nodules, and hypersomnia, as well as COPD, asthma, interstitial lung disease, and obstructive sleep apnea",
        "Interpreted diagnostic tests including pulmonary function tests, chest CT and radiographs, pleural fluid analysis"
    ] } },
    { OverrideHighlights = { target = "Women's Health", highlights = [
        "Performed comprehensive Well Woman exams including breast and pelvic exams, STI testing, contraception and preventive health counseling, and routine prenatal care",
        "Assessed common complaints, including breast mass, abnormal uterine bleeding, dyspareunia, pelvic pain, and perimenopause for a diverse patient population, ranging from young adult to geriatric",
        "Performed and assisted with subcutaneous hormone pellet implantation, colposcopy, IUD insertion, LEEP"
    ] } },
    { OverrideHighlights = { target = "Family Medicine", highlights = [
        "Obtained histories, performed physical exams, and reviewed labs and diagnostic studies for up to 13 patients/day in a fast-paced outpatient clinic serving a diverse patient population",
        "Educated patients on disease management and prevention, especially emphasizing preventive health screenings and lifestyle modifications for chronic cardiovascular diseases, obesity, and diabetes mellitus"
    ] } },
    { OverrideHighlights = { target = "Neurology", highlights = [
        "Evaluated common complaints including headache, neuropathy, vestibular disorders, memory loss, and concussion, utilizing findings from comprehensive history-taking and physical exams",
        "Observed chemodenervation injections and nerve blocks for refractory headaches and neuromuscular disorders"
    ] } },
]
project = [
    { OverrideHighlights = { target = "HEAL 24th Annual Summit", highlights = [
        "Presented Master’s Project at local maternal and child health conference: Yan J, Zwernemann R, Holmes V, Brosnan A. _Ruptured ovarian pregnancy: an important differential for abdominal pain_. Poster presented at: Health Equity Alliance of Tarrant County Summit 2025; September 18 2025; Hurst, Texas"
    ] } }
]
